services:
  nacos:
    image: nacos/nacos-server:${NACOS_VERSION}
    container_name: nacos-standalone
    environment:
      PREFER_HOST_MODE: hostname
      MODE: standalone
      NACOS_AUTH_ENABLE: true
      NACOS_AUTH_IDENTITY_KEY: UNFNg7774GvnW9go
      NACOS_AUTH_IDENTITY_VALUE: gjew8AF0BW7qewCK
      NACOS_AUTH_TOKEN: UG9VUXJLZm9McHhVUkVTVG53SVYzaFRCZ21kbVM5Z2IK=
    volumes:
      - ./standalone-logs/:/home/nacos/logs
    ports:
      - "8080:8080"
      - "8848:8848"
      - "9848:9848"